name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  build:
    name: Test with ${{ matrix.go-version }} on ${{ matrix.vm-os }}
    runs-on: ${{ matrix.vm-os }}
    env:
      CI_REPORT: ${{ matrix.vm-os == 'ubuntu-20.04' && matrix.go-version == '1.18.10' }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        vm-os: [
          ubuntu-20.04,
          macos-13,
          macos-14,
          windows-2022
        ]
        go-version: [
          1.18.10,
          1.19.13,
          1.20.14,
          1.21.9,
          1.22.2,
        ]
    permissions:
      contents: read
    # Steps to execute
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Go Build
        run: |
          export
          git status
          go version
          go mod download
      - name: Test
        run: |
          go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt -count 1 ./...
          go test -parallel=4 -run="none" -benchtime="2s" -benchmem -bench=.
      - name: Upload Coverage Reports to Codecov
        if: ${{ fromJSON(env.CI_REPORT) }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
      - name: Upload Coverage Reports to Codacy
        if: ${{ fromJSON(env.CI_REPORT) }}
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run:
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.txt
      - name: Analyze on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          # Setup
          wget -cqL https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-i686-unknown-linux-musl.tar.gz -O tokei.tgz
          tar zxf tokei.tgz tokei && chmod +x tokei && $SUDO mv tokei /usr/local/bin && rm tokei.tgz
          wget -cqL https://github.com/mgechev/revive/releases/download/v1.3.7/revive_linux_amd64.tar.gz -O revive.tgz
          tar zxf revive.tgz revive && chmod +x revive && $SUDO mv revive /usr/local/bin && rm revive.tgz
          wget -cqL https://raw.githubusercontent.com/1set/meta/master/revive.toml -O revive.toml
          # Analyze
          echo "# Analysis on Linux" > $GITHUB_STEP_SUMMARY
          uname -a >> $GITHUB_STEP_SUMMARY
          # --- count lines of code
          echo "## Tokei Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          tokei >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
          # --- lint
          echo "## Revive Result" >> $GITHUB_STEP_SUMMARY
          printf '\n```\n' >> $GITHUB_STEP_SUMMARY
          revive -config revive.toml -formatter friendly ./... >> $GITHUB_STEP_SUMMARY
          printf '```\n\n' >> $GITHUB_STEP_SUMMARY
